services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: unless-stopped
    environment:
      TZ: ${TZ:-UTC}
    volumes:
      - ./configuration.yaml:/config/configuration.yaml

  haproxy:
    image: haproxy:latest
    container_name: haproxy
    restart: unless-stopped
    depends_on:
      - homeassistant
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
      - /etc/ssl/certs/lego:/etc/ssl:ro